import express from 'express';

import adminRoutes from './admin.routes.js';
import agentRoutes from './agent.routes.js';
import agentAppRoutes from './agentApp.routes.js';
import authRoutes from './auth.routes.js';
import buyRoutes from './buy.routes.js';
import buyCategoryRoutes from './buyCategory.routes.js';
import buyProductRoutes from './buyProduct.routes.js';
import buySuperCategoryRoutes from './buySuperCategory.routes.js';
import categoryRoutes from './category.routes.js';
import contactRoutes from './contact.routes.js';
import financeRoutes from './finance.routes.js';
import partnerRoutes from './partner.routes.js';
import partnerPermissionRoutes from './partnerPermission.routes.js';
import pickupRoutes from './pickup.routes.js';
import productRoutes from './product.routes.js';
import salesRoutes from './sales.routes.js';
import sellRoutes from './sell.routes.js';
import sellAccessoryRoutes from './sellAccessory.routes.js';
import sellConfigRoutes from './sellConfig.routes.js';
import sellDefectRoutes from './sellDefect.routes.js';
import sellOfferSessionRoutes from './sellOfferSession.routes.js';
import sellOrderRoutes from './sellOrder.routes.js';
import sellProductRoutes from './sellProduct.routes.js';
import sellQuestionRoutes from './sellQuestion.routes.js';
import sellSuperCategoryRoutes from './sellSuperCategory.routes.js';
import seriesRoutes from './series.routes.js';
import uploadRoutes from './upload.routes.js';
import userRoutes from './user.routes.js';
import vendorRoutes from './vendor.routes.js';
import walletRoutes from './wallet.routes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/categories', categoryRoutes);
router.use('/buy-super-categories', buySuperCategoryRoutes);
router.use('/sell-super-categories', sellSuperCategoryRoutes);
router.use('/series', seriesRoutes);
router.use('/buy-categories', buyCategoryRoutes);
router.use('/buy-products', buyProductRoutes);
router.use('/user', userRoutes);
router.use('/products', productRoutes);
router.use('/partners', partnerRoutes);
router.use('/partner', partnerRoutes);
router.use('/partner-permissions', partnerPermissionRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/finance', financeRoutes);
router.use('/vendor', vendorRoutes);
router.use('/sell', sellRoutes);
router.use('/buy', buyRoutes);
router.use('/sales', salesRoutes);
router.use('/wallet', walletRoutes);
router.use('/upload', uploadRoutes);
router.use('/contact', contactRoutes);

router.use('/sell-products', sellProductRoutes);
router.use('/sell-questions', sellQuestionRoutes);
router.use('/sell-defects', sellDefectRoutes);
router.use('/sell-accessories', sellAccessoryRoutes);
router.use('/sell-config', sellConfigRoutes);
router.use('/sell-sessions', sellOfferSessionRoutes);
router.use('/sell-orders', sellOrderRoutes);
router.use('/pickups', pickupRoutes);
router.use('/agent', agentRoutes);
router.use('/agent-app', agentAppRoutes);

export default router;
