import express from 'express';
const router = express.Router();

import authRoutes from './auth.routes';
import categoryRoutes from './category.routes';
import buySuperCategoryRoutes from './buySuperCategory.routes';
import sellSuperCategoryRoutes from './sellSuperCategory.routes';
import buyCategoryRoutes from './buyCategory.routes';
import buyProductRoutes from './buyProduct.routes';
import userRoutes from './user.routes';
import productRoutes from './product.routes';
import partnerRoutes from './partner.routes';
import partnerPermissionRoutes from './partnerPermission.routes';
import adminRoutes from './admin.routes';
import vendorRoutes from './vendor.routes';
import sellRoutes from './sell.routes';
import buyRoutes from './buy.routes';
import salesRoutes from './sales.routes';
import walletRoutes from './wallet.routes';
import uploadRoutes from './upload.routes';
import contactRoutes from './contact.routes';
import sellProductRoutes from './sellProduct.routes';
import sellQuestionRoutes from './sellQuestion.routes';
import sellDefectRoutes from './sellDefect.routes';
import sellAccessoryRoutes from './sellAccessory.routes';
import sellConfigRoutes from './sellConfig.routes';
import sellOfferSessionRoutes from './sellOfferSession.routes';
import sellOrderRoutes from './sellOrder.routes';
import pickupRoutes from './pickup.routes';
import agentRoutes from './agent.routes';
import agentAppRoutes from './agentApp.routes';

router.use('/auth', authRoutes);
router.use('/categories', categoryRoutes);
router.use('/buy-super-categories', buySuperCategoryRoutes);
router.use('/sell-super-categories', sellSuperCategoryRoutes);
router.use('/buy-categories', buyCategoryRoutes);
router.use('/buy-products', buyProductRoutes);
router.use('/user', userRoutes);
router.use('/products', productRoutes);
router.use('/partners', partnerRoutes);
router.use('/partner', partnerRoutes);
router.use('/partner-permissions', partnerPermissionRoutes);
router.use('/admin', adminRoutes);
router.use('/vendor', vendorRoutes);
router.use('/sell', sellRoutes);
router.use('/buy', buyRoutes);
router.use('/sales', salesRoutes);
router.use('/wallet', walletRoutes);
router.use('/upload', uploadRoutes);
router.use('/contact', contactRoutes);

router.use('/sell-products', sellProductRoutes);
router.use('/sell-questions', sellQuestionRoutes);
router.use('/sell-defects', sellDefectRoutes);
router.use('/sell-accessories', sellAccessoryRoutes);
router.use('/sell-config', sellConfigRoutes);
router.use('/sell-sessions', sellOfferSessionRoutes);
router.use('/sell-orders', sellOrderRoutes);
router.use('/pickups', pickupRoutes);
router.use('/agent', agentRoutes);
router.use('/agent-app', agentAppRoutes);

export default router;
